/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "filament.exports.download": [
        {
            "name": "export",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.imports.failed-rows.download": [
        {
            "name": "import",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.admin.auth.logout": [],
    "filament.admin.pages.dashboard": [],
    "filament.admin.resources.carts.index": [],
    "filament.admin.resources.carts.create": [],
    "filament.admin.resources.carts.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.orders.index": [],
    "filament.admin.resources.orders.create": [],
    "filament.admin.resources.orders.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.orders.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.products.index": [],
    "filament.admin.resources.products.create": [],
    "filament.admin.resources.products.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.users.index": [],
    "filament.admin.resources.users.create": [],
    "filament.admin.resources.users.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "home": [],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
