declare namespace App.Data {
    export type AddressData = {
        id: number | null;
        user_id: number | null;
        session_id: string | null;
        first_name: string | null;
        last_name: string | null;
        email: string | null;
        phone: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        country: string | null;
        postal_code: string | null;
        is_default: boolean | null;
        additional_info: string | null;
        user: App.Data.UserData | null;
    };
    export type CartData = {
        product: App.Data.ProductData;
        item: string;
        price: number;
        id: number | null;
        discount: number | null;
        vat: number | null;
        qty: number | null;
        total: number | null;
        note: string | null;
        options: Array<any> | null;
        is_active: boolean | null;
        created_at: string | null;
        updated_at: string | null;
        user: App.Data.UserData | null;
    };
    export type CategoryData = {
        products: Array<App.Data.ProductData>;
        slug: string;
        id: number | null;
        parent_id: number | null;
        for: string | null;
        type: string | null;
        name: string | null;
        description: string | null;
        icon: string | null;
        color: string | null;
        is_active: boolean;
        show_in_menu: boolean;
        created_at: string | null;
        updated_at: string | null;
    };
    export type CouponData = {
        code: string;
        type: App.Enums.CouponDiscountType;
        amount: number;
        is_limited: boolean;
        end_at: string | null;
        use_limit: number | null;
        use_limit_by_user: number | null;
        order_total_limit: number | null;
        is_activated: boolean;
        is_marketing: boolean;
        marketer_name: string | null;
        marketer_type: string | null;
        marketer_amount: number | null;
        marketer_amount_max: number | null;
        marketer_show_amount_max: boolean;
        marketer_hide_total_sales: boolean;
        is_used: number | null;
        apply_to: Array<any> | null;
        except: Array<any> | null;
        created_at: string | null;
        updated_at: string | null;
        id: number | null;
    };
    export type DeliveryData = {
        name: string;
        phone: string | null;
        address: string | null;
        shipping_vendor_id: number | null;
        is_activated: boolean;
        created_at: string | null;
        updated_at: string | null;
        shippingVendor: App.Data.ShippingVendorData | null;
        shippingPrices: Array<App.Data.ShippingPriceData> | null;
        id: number | null;
    };
    export type GiftCardData = {
        name: string;
        code: string;
        balance: number;
        user_id: number;
        is_activated: boolean;
        is_expired: boolean;
        created_at: string | null;
        updated_at: string | null;
        user: App.Data.UserData | null;
        id: number | null;
    };
    export type OrderData = {
        ordersItems: Array<App.Data.OrdersItemData>;
        name: string | null;
        phone: string | null;
        id: number | null;
        user_id: number | null;
        coupon_id: number | null;
        shipper_id: number | null;
        shipping_vendor_id: number | null;
        uuid: string | null;
        type: string | null;
        flat: string | null;
        address: string | null;
        address_id: string | null;
        country: string | null;
        area: string | null;
        city: string | null;
        source: string | null;
        shipper_vendor: string | null;
        total: number;
        discount: number | null;
        shipping: number | null;
        has_free_shipping: boolean | null;
        vat: number | null;
        status: string | null;
        is_approved: boolean | null;
        is_closed: boolean | null;
        is_on_table: boolean | null;
        table: string | null;
        notes: string | null;
        has_returns: boolean;
        return_total: number | null;
        reason: string | null;
        is_payed: boolean | null;
        payment_method: string | null;
        created_at: string | null;
        updated_at: string | null;
        user: App.Data.UserData | null;
        coupon: App.Data.CouponData | null;
    };
    export type OrderLogData = {
        id: number | null;
        order_id: number | null;
        user_id: number | null;
        status: string | null;
        note: string | null;
        created_at: string | null;
        updated_at: string | null;
        order: App.Data.OrderData | null;
        user: App.Data.UserData | null;
    };
    export type OrderMetaData = {
        id: number | null;
        order_id: number | null;
        key: string | null;
        value: any;
        type: string | null;
        group: string | null;
        created_at: string | null;
        updated_at: string | null;
        order: App.Data.OrderData | null;
    };
    export type OrdersItemData = {
        id: number | null;
        order_id: number | null;
        account_id: number | null;
        product_id: number | null;
        refund_id: number | null;
        item: string | null;
        price: number | null;
        discount: number | null;
        vat: number | null;
        total: number | null;
        returned: number | null;
        qty: number | null;
        code: string | null;
        returned_qty: number | null;
        is_free: boolean | null;
        is_returned: boolean | null;
        options: Array<any> | null;
        created_at: string | null;
        updated_at: string | null;
        user: App.Data.UserData | null;
        order: App.Data.OrderData | null;
        product: App.Data.ProductData | null;
    };
    export type ProductData = {
        variations: Array<App.Data.VariationData>;
        slug: string;
        id: number | null;
        category_id: number | null;
        user_id: number | null;
        feature_image: string | null;
        thumbnail_image: string | null;
        gallery_images: Array<string>;
        name: string | null;
        description: string | null;
        price: number;
        discount: number | null;
        discount_to: string | null;
        vat: number | null;
        is_in_stock: boolean | null;
        is_activated: boolean | null;
        is_shipped: boolean | null;
        is_trend: boolean | null;
        has_options: boolean | null;
        has_multi_price: boolean | null;
        has_unlimited_stock: boolean | null;
        has_max_cart: boolean | null;
        min_cart: number | null;
        max_cart: number | null;
        has_stock_alert: boolean | null;
        min_stock_alert: number | null;
        max_stock_alert: number | null;
        created_at: string | null;
        updated_at: string | null;
        category: App.Data.CategoryData | null;
        artist: App.Data.UserData | null;
    };
    export type ProductMetaData = {
        id: number | null;
        product_id: number | null;
        key: string | null;
        value: any;
        model_id: number | null;
        model_type: string | null;
        created_at: string | null;
        updated_at: string | null;
    };
    export type ReferralCodeData = {
        user_id: number;
        name: string;
        code: string;
        counter: number;
        is_activated: boolean;
        is_public: boolean;
        created_at: string | null;
        updated_at: string | null;
        user: App.Data.UserData | null;
        id: number | null;
    };
    export type ShippingPriceData = {
        id: number | null;
        shipping_vendor_id: number | null;
        delivery_id: number | null;
        country: string | null;
        city: string | null;
        area: string | null;
        type: string;
        price: number;
        created_at: string | null;
        updated_at: string | null;
        shippingVendor: App.Data.ShippingVendorData | null;
        delivery: App.Data.DeliveryData | null;
    };
    export type ShippingVendorData = {
        name: string;
        phone: string | null;
        address: string | null;
        contact_person: string | null;
        delivery_estimation: string | null;
        price: number;
        is_activated: boolean;
        created_at: string | null;
        updated_at: string | null;
        deliveries: Array<App.Data.DeliveryData> | null;
        shippingPrices: Array<App.Data.ShippingPriceData> | null;
        id: number | null;
    };
    export type SubscribeData = {
        id: number | null;
        user_id: number;
        period: App.Enums.SubscriptionPeriod;
        start_at: string | null;
        end_at: string | null;
        status: App.Enums.SubscribeStatus;
        plan: App.Data.SubscribePlanData | null;
        created_at: string | null;
        updated_at: string | null;
    };
    export type SubscribePlanData = {
        id: number;
        name: string;
        price: number;
        is_active: boolean;
        annual_price: number | null;
        is_popular: boolean;
        description: string | null;
        features_list: Array<any> | null;
        annual_discount: number | null;
        created_at: string | null;
        updated_at: string | null;
        deleted_at: string | null;
    };
    export type TypeData = {
        id: number | null;
        parent_id: number | null;
        order: number | null;
        for: string | null;
        name: string | null;
        key: string | null;
        type: string | null;
        description: string | null;
        color: string | null;
        icon: string | null;
        model_type: string | null;
        model_id: number | null;
        is_activated: boolean | null;
        created_at: string | null;
        updated_at: string | null;
    };
    export type TypesMetaData = {
        id: number | null;
        type_id: number | null;
        model_id: number | null;
        model_type: string | null;
        key: string | null;
        value: any;
        created_at: string | null;
        updated_at: string | null;
        type: App.Data.TypeData | null;
    };
    export type UserData = {
        id: number | null;
        name: string | null;
        email: string | null;
        email_verified_at: string | null;
        created_at: string | null;
        updated_at: string | null;
    };
    export type VariationData = {
        name: string | null;
        value: Array<App.Data.VariationValueData>;
    };
    export type VariationValueData = {
        value: string | null;
        has_custom_price: boolean;
        price_for: string;
        price: number;
        vat: number;
        discount: number;
        discount_to: number;
        has_color: boolean;
        color: string;
    };
    export type WishlistData = {
        id: number | null;
        user_id: number | null;
        product_id: number | null;
        created_at: string | null;
        updated_at: string | null;
    };
}
declare namespace App.Enums {
    export type CouponDiscountType = 'percentage_coupon' | 'discount_coupon';
    export type SubscribeStatus = 'Active' | 'Inactive' | 'Cancelled' | 'Paused' | 'Scheduled' | 'pending' | 'failed';
    export type SubscriptionPeriod = 'Monthly' | 'Annually';
}
