<?php

namespace App\Filament\Admin\Resources\OrderResource\Pages;

use App\Filament\Admin\Resources\OrderResource;
use Filament\Actions;
use Filament\Resources\Pages\ViewRecord;

class ViewOrder extends ViewRecord
{
    protected static string $resource = OrderResource::class;

    protected static string $view = 'filament-ecommerce::orders.show';

    protected function getHeaderActions(): array
    {
        return [
            Actions\Action::make('print')
                ->icon('heroicon-o-printer')
                ->label(trans('filament-ecommerce::messages.orders.actions.print'))
                ->openUrlInNewTab()
                ->url(route('order.print', $this->getRecord()->id)),
            Actions\DeleteAction::make()->icon('heroicon-o-trash'),
            Actions\EditAction::make()->icon('heroicon-o-pencil-square')->color('warning'),
        ];
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        $data['items'] = $this->getRecord()->ordersItems->toArray();

        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }
}
